export const optionsArray = [
  {
    label: "Hi",
    value: "hi",
    accountNumber: "82622823",
    sortCode: "400520",
    accountType: "Business A/C",
    accountHolderName: "Abc",
    fullName: "abcd, Mr.efg",
    accountHolderType: "ACCOUNT HOLDER",
    balance: "-18896454",
    balanceText: "GBL",
  },
  {
    label: "Hello",
    value: "hello",
    accountNumber: "82622893",
    sortCode: "800520",
    accountType: "Business A/C",
    accountHolderName: "Abc",
    fullName: "abcd, Mr.efg",
    accountHolderType: "ACCOUNT HOLDER",
    balance: "3496455",
    balanceText: "GBL",
  },
];
