export const optionsArray = [
  {
    label: "Hi",
    value: "hi",
    accountNumber: "82622823",
    sortCode: "400520",
    accountType: "Business A/C",
    accountHolderName: "Abc",
    fullName: "abcd, Mr.efg",
    accountHolderType: "ACCOUNT HOLDER",
    balance: "15.73",
    balanceText: "GBL",
  },
  {
    label: "Hello",
    value: "hello",
    accountNumber: "5962 9380",
    sortCode: "708060",
    accountType: "Commercial Card",
    accountHolderName: "Luke Co",
    fullName: "Skywalker, Luke/Mr",
    accountHolderType: "CARDHOLDER",
    balance: "14.25",
    balanceText: "GBL",
  },
];
